# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # Specify the Docker image to use for this job
    runs-on: ubuntu-latest  # GitHub still requires a host runner
    container:
      image: amazoncorretto:17.0.13-al2023-headless

    steps:
      # Checkout the code
      - name: Check out repository
        uses: actions/checkout@v4

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Run Maven tests
      - name: Run Maven tests
        run: mvn clean test